Crypto finance
dialite/crypto-finance-metrics pull request #1
Opened 2023-01-06 00:13 UTC by dialite

This mobile web application project has the following features:

Capstone Project- Crypto Finance Metrics

- A single-page application (SPA) built with React and Redux.
- The data retrieved from the API is stored in the Redux store.
- Obtain and display crypto data from CoinStats.API.

- Set up a search bar to be able to filter based on the company's names.

- Create tests using React Testing Library.
- Deployed the project and added the live demo link in the README.md file.

2023-01-06 12:07 UTC, rloterh requested changes
Hi Raymond, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project, but you are almost there! 🚦 🚦   🏃 

## Highlights 👍  
- Nice presentation of this project
- Good job acknowledging Nelson Sakwa on Behance for the [Original design idea](https://www.behance.net/sakwadesignstudio).
- API fetch properly implemented
- State management with Redux properly implemented
- Navigation working as intended
- Properly implemented unit and integration test 
- Filter works great! 💪 
- Good ReadMe

## Required Changes ♻️
_Kindly check the inline comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

_Kindly check the inline comments marked **[OPTIONAL]** under the review._

Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-06 12:07 UTC, rloterh commented on README.md
> +  <img src="murple_logo.png" alt="logo" width="140"  height="auto" />
- [ ] OPTIONAL
Your logo is broken. Kindly ensure to fix it.

2023-01-07 02:06 UTC, dialite commented
Thank you for the feedback review. All observation duly implemented.

2023-01-07 02:28 UTC, mwanawabangona approved these changes
Hi @dialite

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations!  
![](https://camo.githubusercontent.com/d348d0cdaa16b202354d12402e048f52cd4d589b4ec0e55f07d62c2f22753376/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f373246634a6d4c7a4964594a646d44652f67697068792e676966)

## Highlights
*   No linter errors :heavy_check_mark:
*   Repo looks professional :briefcase:
*   Solid pull request scroll
*   Good quality commits
*   Good job implementing the requested changes !! :clap: :clap: :clap:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-07 02:36 UTC, merged